### ISSUE TITLE
Load local fonts

### ISSUE THREAD

**Issue by rashil2000** [AmraniCh/github-code-font-changer#12]
Hi!

Thanks for this great extension! Works very nicely for me.

Would it be possible to make it load the computer's locally installed fonts? I have some manually patched fonts that I'd like to use.

Currently, I work around this be adding an entry to the `fonts` object in background.js.

Cheers!

**Comment by AmraniCh** [comment]
Hey, Thanks for opening this issue and for your feedback about this extension.

Allows using local fonts is very useful and practical, I've updated the [TODO list file](https://github.com/AmraniCh/github-code-font-changer/blob/master/TODO.md) with this feature request, and hopefully this feature will be added soon in the next versions.
