### ISSUE TITLE
Can you add the Agave font, or in that case, all of the programming fonts?

### ISSUE THREAD

**Issue by pragmaticmero** [AmraniCh/github-code-font-changer#13]
Plz
https://www.programmingfonts.org/#agave
https://www.programmingfonts.org

**Comment by AmraniCh** [comment]
We accept only open source fonts, I don't know this font is free or not and I can't find it in [Google font](https://fonts.google.com/) library, so I suppose it not free, is so we can't add it to this extension.

**Comment by dzmien** [comment]
> We accept only open source fonts, I don't know this font whether is free or not and I can't find it in [Google font](https://fonts.google.com/) library, so I suppose it not free, if so we can't add it to this extension.

There appears to be an upstream link next to each font listed on the left side of the programmingfonts.org website. It is small and easy to miss. Anyway, according to [Agave's README on GitHub](https://github.com/blobject/agave/), the font is

>"Free to use, peruse, and diffuse – everything (font files, glyph designs, glyph databases, and documentation) is released under the [MIT license](https://github.com/blobject/agave/blob/master/LICENSE)."

**Comment by AmraniCh** [comment]
@dzmien I just released the version 2, you can now use your local fonts in the extension beside the extension fonts, waiting for Google to approve the new changes and update the extension in chrome store, thank you!

**Comment by dzmien** [comment]
@AmraniCh very cool, that sounds like a much more ideal solution. Thanks for the heads-up!
