### ISSUE TITLE
No font options available after installation

### ISSUE THREAD

**Issue by chinleung** [AmraniCh/github-code-font-changer#15]
Hi,

I've installed the extension via the Chrome store and I have no options in the dropdown.

<img width="285" alt="image" src="https://user-images.githubusercontent.com/19669331/213558511-1a51fa18-c89b-44d3-9c2b-714c520a2073.png">

**Comment by AmraniCh** [comment]
Hi, thanks for opening the issue.
I want to know which chrome version you have please?

**Comment by chinleung** [comment]
@AmraniCh I have the latest version.

> Version 109.0.5414.87 (Official Build) (arm64)

**Comment by AmraniCh** [comment]
Hey, this filed is not a select element, it is a datalist HTML element, try to click on the arrow on the right so the list of available fonts can be shown to you.
![2023-02-18_151054](https://user-images.githubusercontent.com/49124992/219870485-48a1c276-273b-4ba1-b341-afe3792b9dc4.png)
