### ISSUE TITLE
local font not loading

### ISSUE THREAD

**Issue by ericniebler** [AmraniCh/github-code-font-changer#19]
i have a lovely local code font that i purchased recently. i am having no luck getting it to load in the font-changer. i am using Ubuntu. when i open the system 'fonts' settings, i see the name of the font i want to use: Comic Code Ligatures. (yes, comic code. don't judge me.) when i type that font name into the extension, the code font on github reverts to some awful default. see attached screenshot.

am i doing something wrong?

![image](https://github.com/user-attachments/assets/d046f9b5-4dbd-48ac-b4d1-414707683a3c)

EDIT: i have cloned your repo and can load the extension from source. if there is a way i can patch the extention to load my font, that would be an acceptable workaround.

also: thank you for this nice extension! and i like the logo. clever.

**Comment by ericniebler** [comment]
after updating my OS and rebooting, the problem went away. the results look great! :-D

**Comment by AmraniCh** [comment]
Hey @ericniebler, Great news, thanks for opening this issue.
